# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _simV2
else:
    import _simV2

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def VisItDisconnect():
    return _simV2.VisItDisconnect()

def VisItFinalize():
    return _simV2.VisItFinalize()

def VisItProcessEngineCommand():
    return _simV2.VisItProcessEngineCommand()

def VisItSetBroadcastIntFunction(bicb):
    return _simV2.VisItSetBroadcastIntFunction(bicb)

def VisItSetBroadcastIntFunction2(cb, arg2):
    return _simV2.VisItSetBroadcastIntFunction2(cb, arg2)

def VisItSetBroadcastStringFunction(bscb):
    return _simV2.VisItSetBroadcastStringFunction(bscb)

def VisItSetBroadcastStringFunction2(cb, arg2):
    return _simV2.VisItSetBroadcastStringFunction2(cb, arg2)

def VisItSetParallel(arg1):
    return _simV2.VisItSetParallel(arg1)

def VisItSetParallelRank(arg1):
    return _simV2.VisItSetParallelRank(arg1)

def VisItSetDirectory(arg1):
    return _simV2.VisItSetDirectory(arg1)

def VisItSetOptions(arg1):
    return _simV2.VisItSetOptions(arg1)

def VisItSetupEnvironment():
    return _simV2.VisItSetupEnvironment()

def VisItSetupEnvironment2(env):
    return _simV2.VisItSetupEnvironment2(env)

def VisItGetEnvironment():
    return _simV2.VisItGetEnvironment()

def VisItInitializeSocketAndDumpSimFile(name, comment, path, inputfile, guifile, absoluteFilename):
    return _simV2.VisItInitializeSocketAndDumpSimFile(name, comment, path, inputfile, guifile, absoluteFilename)

def VisItDetectInput(blocking, consoledesc):
    return _simV2.VisItDetectInput(blocking, consoledesc)

def VisItDetectInputWithTimeout(blocking, timeout_usec, consoledesc):
    return _simV2.VisItDetectInputWithTimeout(blocking, timeout_usec, consoledesc)

def VisItGetSockets(*args):
    return _simV2.VisItGetSockets(*args)

def VisItAttemptToCompleteConnection():
    return _simV2.VisItAttemptToCompleteConnection()

def VisItReadConsole(*args):
    return _simV2.VisItReadConsole(*args)

def VisItSetSlaveProcessCallback(spcb):
    return _simV2.VisItSetSlaveProcessCallback(spcb)

def VisItSetSlaveProcessCallback2(cb, arg2):
    return _simV2.VisItSetSlaveProcessCallback2(cb, arg2)

def VisItSetCommandCallback(cb, cbdata1):
    return _simV2.VisItSetCommandCallback(cb, cbdata1)

def VisItTimeStepChanged():
    return _simV2.VisItTimeStepChanged()

def VisItUpdatePlots():
    return _simV2.VisItUpdatePlots()

def VisItExecuteCommand(arg1):
    return _simV2.VisItExecuteCommand(arg1)

def VisItIsConnected():
    return _simV2.VisItIsConnected()

def VisItIsRuntimeLoaded():
    return _simV2.VisItIsRuntimeLoaded()

def VisItGetLastError():
    return _simV2.VisItGetLastError()

def VisItSynchronize():
    return _simV2.VisItSynchronize()

def VisItEnableSynchronize(arg1):
    return _simV2.VisItEnableSynchronize(arg1)

def VisItDebug1(*args):
    return _simV2.VisItDebug1(*args)

def VisItDebug2(*args):
    return _simV2.VisItDebug2(*args)

def VisItDebug3(*args):
    return _simV2.VisItDebug3(*args)

def VisItDebug4(*args):
    return _simV2.VisItDebug4(*args)

def VisItDebug5(*args):
    return _simV2.VisItDebug5(*args)

def VisItOpenTraceFile(filename):
    return _simV2.VisItOpenTraceFile(filename)

def VisItCloseTraceFile():
    return _simV2.VisItCloseTraceFile()

def VisItSaveWindow(filename, width, height, format):
    return _simV2.VisItSaveWindow(filename, width, height, format)

def VisItBeginCinema(h, file_cdb, dbspec, composite, imgformat, width, height, cameratype, nphi, ntheta, varnames):
    return _simV2.VisItBeginCinema(h, file_cdb, dbspec, composite, imgformat, width, height, cameratype, nphi, ntheta, varnames)

def VisItSaveCinema(h, time):
    return _simV2.VisItSaveCinema(h, time)

def VisItEndCinema(h):
    return _simV2.VisItEndCinema(h)

def VisItSetMPICommunicator(mpicom):
    return _simV2.VisItSetMPICommunicator(mpicom)

def VisItSetMPICommunicator_f(mpicom):
    return _simV2.VisItSetMPICommunicator_f(mpicom)

def VisItInitializeRuntime():
    return _simV2.VisItInitializeRuntime()

def VisItGetMemory():
    return _simV2.VisItGetMemory()

def VisItExportDatabase(filename, format, variables):
    return _simV2.VisItExportDatabase(filename, format, variables)

def VisItExportDatabaseWithOptions(filename, format, variables, options):
    return _simV2.VisItExportDatabaseWithOptions(filename, format, variables, options)

def VisItRestoreSession(filename):
    return _simV2.VisItRestoreSession(filename)

def VisItSetActivateTimestep(cb, cbdata1):
    return _simV2.VisItSetActivateTimestep(cb, cbdata1)

def VisItSetGetMetaData(cb, cbdata1):
    return _simV2.VisItSetGetMetaData(cb, cbdata1)

def VisItSetGetMesh(cb, cbdata1):
    return _simV2.VisItSetGetMesh(cb, cbdata1)

def VisItSetGetMaterial(cb, cbdata1):
    return _simV2.VisItSetGetMaterial(cb, cbdata1)

def VisItSetGetSpecies(cb, cbdata1):
    return _simV2.VisItSetGetSpecies(cb, cbdata1)

def VisItSetGetVariable(cb, cbdata1):
    return _simV2.VisItSetGetVariable(cb, cbdata1)

def VisItSetGetMixedVariable(cb, cbdata1):
    return _simV2.VisItSetGetMixedVariable(cb, cbdata1)

def VisItSetGetCurve(cb, cbdata1):
    return _simV2.VisItSetGetCurve(cb, cbdata1)

def VisItSetGetDomainList(cb, cbdata1):
    return _simV2.VisItSetGetDomainList(cb, cbdata1)

def VisItSetGetDomainBoundaries(cb, cbdata1):
    return _simV2.VisItSetGetDomainBoundaries(cb, cbdata1)

def VisItSetGetDomainNesting(cb, cbdata1):
    return _simV2.VisItSetGetDomainNesting(cb, cbdata1)

def VisItSetWriteBegin(cb, cbdata1):
    return _simV2.VisItSetWriteBegin(cb, cbdata1)

def VisItSetWriteEnd(cb, cbdata1):
    return _simV2.VisItSetWriteEnd(cb, cbdata1)

def VisItSetWriteMesh(cb, cbdata1):
    return _simV2.VisItSetWriteMesh(cb, cbdata1)

def VisItSetWriteVariable(cb, cbdata1):
    return _simV2.VisItSetWriteVariable(cb, cbdata1)

def VisItUI_clicked(name, cb, cbdata2):
    return _simV2.VisItUI_clicked(name, cb, cbdata2)

def VisItUI_stateChanged(name, cb, cbdata2):
    return _simV2.VisItUI_stateChanged(name, cb, cbdata2)

def VisItUI_valueChanged(name, cb, cbdata2):
    return _simV2.VisItUI_valueChanged(name, cb, cbdata2)

def VisItUI_textChanged(name, cb, cbdata2):
    return _simV2.VisItUI_textChanged(name, cb, cbdata2)

def VisItUI_cellChanged(name, cb, cbdata2):
    return _simV2.VisItUI_cellChanged(name, cb, cbdata2)

def VisItUI_setValueI(name, value, enabled):
    return _simV2.VisItUI_setValueI(name, value, enabled)

def VisItUI_setValueD(name, value, enabled):
    return _simV2.VisItUI_setValueD(name, value, enabled)

def VisItUI_setValueV(name, x, y, z, enabled):
    return _simV2.VisItUI_setValueV(name, x, y, z, enabled)

def VisItUI_setValueS(name, value, enabled):
    return _simV2.VisItUI_setValueS(name, value, enabled)

def VisItUI_setListValueI(name, row, value, editable, enabled):
    return _simV2.VisItUI_setListValueI(name, row, value, editable, enabled)

def VisItUI_setListValueD(name, row, value, editable, enabled):
    return _simV2.VisItUI_setListValueD(name, row, value, editable, enabled)

def VisItUI_setListValueV(name, row, x, y, z, editable, enabled):
    return _simV2.VisItUI_setListValueV(name, row, x, y, z, editable, enabled)

def VisItUI_setListValueS(name, row, value, editable, enabled):
    return _simV2.VisItUI_setListValueS(name, row, value, editable, enabled)

def VisItUI_setTableValueI(name, row, col, value, enabled):
    return _simV2.VisItUI_setTableValueI(name, row, col, value, enabled)

def VisItUI_setTableValueD(name, row, col, value, enabled):
    return _simV2.VisItUI_setTableValueD(name, row, col, value, enabled)

def VisItUI_setTableValueV(name, row, col, x, y, z, enabled):
    return _simV2.VisItUI_setTableValueV(name, row, col, x, y, z, enabled)

def VisItUI_setTableValueS(name, row, col, value, enabled):
    return _simV2.VisItUI_setTableValueS(name, row, col, value, enabled)

def VisItUI_addStripChartPoint(chart, curve, cycle, value):
    return _simV2.VisItUI_addStripChartPoint(chart, curve, cycle, value)

def VisItAddPlot(plotType, var):
    return _simV2.VisItAddPlot(plotType, var)

def VisItAddOperator(operatorType, applyToAll):
    return _simV2.VisItAddOperator(operatorType, applyToAll)

def VisItDrawPlots():
    return _simV2.VisItDrawPlots()

def VisItDeleteActivePlots():
    return _simV2.VisItDeleteActivePlots()

def VisItSetActivePlots(ids, nids):
    return _simV2.VisItSetActivePlots(ids, nids)

def VisItChangePlotVar(var, all):
    return _simV2.VisItChangePlotVar(var, all)

def VisItSetPlotOptionsC(name, v):
    return _simV2.VisItSetPlotOptionsC(name, v)

def VisItSetPlotOptionsUC(name, v):
    return _simV2.VisItSetPlotOptionsUC(name, v)

def VisItSetPlotOptionsB(name, v):
    return _simV2.VisItSetPlotOptionsB(name, v)

def VisItSetPlotOptionsI(name, v):
    return _simV2.VisItSetPlotOptionsI(name, v)

def VisItSetPlotOptionsL(name, v):
    return _simV2.VisItSetPlotOptionsL(name, v)

def VisItSetPlotOptionsF(name, v):
    return _simV2.VisItSetPlotOptionsF(name, v)

def VisItSetPlotOptionsD(name, v):
    return _simV2.VisItSetPlotOptionsD(name, v)

def VisItSetPlotOptionsS(name, s):
    return _simV2.VisItSetPlotOptionsS(name, s)

def VisItSetPlotOptionsCv(name, v, L):
    return _simV2.VisItSetPlotOptionsCv(name, v, L)

def VisItSetPlotOptionsUCv(name, v, L):
    return _simV2.VisItSetPlotOptionsUCv(name, v, L)

def VisItSetPlotOptionsIv(name, v, L):
    return _simV2.VisItSetPlotOptionsIv(name, v, L)

def VisItSetPlotOptionsLv(name, v, L):
    return _simV2.VisItSetPlotOptionsLv(name, v, L)

def VisItSetPlotOptionsFv(name, v, L):
    return _simV2.VisItSetPlotOptionsFv(name, v, L)

def VisItSetPlotOptionsDv(name, v, L):
    return _simV2.VisItSetPlotOptionsDv(name, v, L)

def VisItSetPlotOptionsSv(name, sv, L):
    return _simV2.VisItSetPlotOptionsSv(name, sv, L)

def VisItSetOperatorOptionsC(name, v):
    return _simV2.VisItSetOperatorOptionsC(name, v)

def VisItSetOperatorOptionsUC(name, v):
    return _simV2.VisItSetOperatorOptionsUC(name, v)

def VisItSetOperatorOptionsB(name, v):
    return _simV2.VisItSetOperatorOptionsB(name, v)

def VisItSetOperatorOptionsI(name, v):
    return _simV2.VisItSetOperatorOptionsI(name, v)

def VisItSetOperatorOptionsL(name, v):
    return _simV2.VisItSetOperatorOptionsL(name, v)

def VisItSetOperatorOptionsF(name, v):
    return _simV2.VisItSetOperatorOptionsF(name, v)

def VisItSetOperatorOptionsD(name, v):
    return _simV2.VisItSetOperatorOptionsD(name, v)

def VisItSetOperatorOptionsS(name, s):
    return _simV2.VisItSetOperatorOptionsS(name, s)

def VisItSetOperatorOptionsCv(name, v, L):
    return _simV2.VisItSetOperatorOptionsCv(name, v, L)

def VisItSetOperatorOptionsUCv(name, v, L):
    return _simV2.VisItSetOperatorOptionsUCv(name, v, L)

def VisItSetOperatorOptionsIv(name, v, L):
    return _simV2.VisItSetOperatorOptionsIv(name, v, L)

def VisItSetOperatorOptionsLv(name, v, L):
    return _simV2.VisItSetOperatorOptionsLv(name, v, L)

def VisItSetOperatorOptionsFv(name, v, L):
    return _simV2.VisItSetOperatorOptionsFv(name, v, L)

def VisItSetOperatorOptionsDv(name, v, L):
    return _simV2.VisItSetOperatorOptionsDv(name, v, L)

def VisItSetOperatorOptionsSv(name, sv, L):
    return _simV2.VisItSetOperatorOptionsSv(name, sv, L)

def VisItSetView2D(v):
    return _simV2.VisItSetView2D(v)

def VisItGetView2D(v):
    return _simV2.VisItGetView2D(v)

def VisItSetView3D(v):
    return _simV2.VisItSetView3D(v)

def VisItGetView3D(v):
    return _simV2.VisItGetView3D(v)
VISIT_INVALID_HANDLE = _simV2.VISIT_INVALID_HANDLE
VISIT_ERROR = _simV2.VISIT_ERROR
VISIT_OKAY = _simV2.VISIT_OKAY
VISIT_NODATA = _simV2.VISIT_NODATA
VISIT_MESHTYPE_UNKNOWN = _simV2.VISIT_MESHTYPE_UNKNOWN
VISIT_MESHTYPE_RECTILINEAR = _simV2.VISIT_MESHTYPE_RECTILINEAR
VISIT_MESHTYPE_CURVILINEAR = _simV2.VISIT_MESHTYPE_CURVILINEAR
VISIT_MESHTYPE_UNSTRUCTURED = _simV2.VISIT_MESHTYPE_UNSTRUCTURED
VISIT_MESHTYPE_POINT = _simV2.VISIT_MESHTYPE_POINT
VISIT_MESHTYPE_CSG = _simV2.VISIT_MESHTYPE_CSG
VISIT_MESHTYPE_AMR = _simV2.VISIT_MESHTYPE_AMR
VISIT_VARCENTERING_NODE = _simV2.VISIT_VARCENTERING_NODE
VISIT_VARCENTERING_ZONE = _simV2.VISIT_VARCENTERING_ZONE
VISIT_VARTYPE_UNKNOWN = _simV2.VISIT_VARTYPE_UNKNOWN
VISIT_VARTYPE_SCALAR = _simV2.VISIT_VARTYPE_SCALAR
VISIT_VARTYPE_VECTOR = _simV2.VISIT_VARTYPE_VECTOR
VISIT_VARTYPE_TENSOR = _simV2.VISIT_VARTYPE_TENSOR
VISIT_VARTYPE_SYMMETRIC_TENSOR = _simV2.VISIT_VARTYPE_SYMMETRIC_TENSOR
VISIT_VARTYPE_MATERIAL = _simV2.VISIT_VARTYPE_MATERIAL
VISIT_VARTYPE_MATSPECIES = _simV2.VISIT_VARTYPE_MATSPECIES
VISIT_VARTYPE_LABEL = _simV2.VISIT_VARTYPE_LABEL
VISIT_VARTYPE_ARRAY = _simV2.VISIT_VARTYPE_ARRAY
VISIT_VARTYPE_MESH = _simV2.VISIT_VARTYPE_MESH
VISIT_VARTYPE_CURVE = _simV2.VISIT_VARTYPE_CURVE
VISIT_ENUMTYPE_NONE = _simV2.VISIT_ENUMTYPE_NONE
VISIT_ENUMTYPE_BY_VALUE = _simV2.VISIT_ENUMTYPE_BY_VALUE
VISIT_ENUMTYPE_BY_RANGE = _simV2.VISIT_ENUMTYPE_BY_RANGE
VISIT_ENUMTYPE_BY_BITMASK = _simV2.VISIT_ENUMTYPE_BY_BITMASK
VISIT_ENUMTYPE_BY_NCHOOSER = _simV2.VISIT_ENUMTYPE_BY_NCHOOSER
VISIT_CMDARG_NONE = _simV2.VISIT_CMDARG_NONE
VISIT_CMDARG_INT = _simV2.VISIT_CMDARG_INT
VISIT_CMDARG_FLOAT = _simV2.VISIT_CMDARG_FLOAT
VISIT_CMDARG_STRING = _simV2.VISIT_CMDARG_STRING
VISIT_SIMMODE_UNKNOWN = _simV2.VISIT_SIMMODE_UNKNOWN
VISIT_SIMMODE_RUNNING = _simV2.VISIT_SIMMODE_RUNNING
VISIT_SIMMODE_STOPPED = _simV2.VISIT_SIMMODE_STOPPED
VISIT_DATATYPE_CHAR = _simV2.VISIT_DATATYPE_CHAR
VISIT_DATATYPE_INT = _simV2.VISIT_DATATYPE_INT
VISIT_DATATYPE_FLOAT = _simV2.VISIT_DATATYPE_FLOAT
VISIT_DATATYPE_DOUBLE = _simV2.VISIT_DATATYPE_DOUBLE
VISIT_DATATYPE_LONG = _simV2.VISIT_DATATYPE_LONG
VISIT_DATATYPE_STRING = _simV2.VISIT_DATATYPE_STRING
VISIT_OWNER_SIM = _simV2.VISIT_OWNER_SIM
VISIT_OWNER_VISIT = _simV2.VISIT_OWNER_VISIT
VISIT_OWNER_COPY = _simV2.VISIT_OWNER_COPY
VISIT_OWNER_VISIT_EX = _simV2.VISIT_OWNER_VISIT_EX
VISIT_MEMORY_CONTIGUOUS = _simV2.VISIT_MEMORY_CONTIGUOUS
VISIT_MEMORY_STRIDED = _simV2.VISIT_MEMORY_STRIDED
VISIT_CELL_BEAM = _simV2.VISIT_CELL_BEAM
VISIT_CELL_TRI = _simV2.VISIT_CELL_TRI
VISIT_CELL_QUAD = _simV2.VISIT_CELL_QUAD
VISIT_CELL_TET = _simV2.VISIT_CELL_TET
VISIT_CELL_PYR = _simV2.VISIT_CELL_PYR
VISIT_CELL_WEDGE = _simV2.VISIT_CELL_WEDGE
VISIT_CELL_HEX = _simV2.VISIT_CELL_HEX
VISIT_CELL_POINT = _simV2.VISIT_CELL_POINT
VISIT_CELL_POLYHEDRON = _simV2.VISIT_CELL_POLYHEDRON
VISIT_CELL_QUADRATIC_EDGE = _simV2.VISIT_CELL_QUADRATIC_EDGE
VISIT_CELL_QUADRATIC_TRI = _simV2.VISIT_CELL_QUADRATIC_TRI
VISIT_CELL_QUADRATIC_QUAD = _simV2.VISIT_CELL_QUADRATIC_QUAD
VISIT_CELL_QUADRATIC_TET = _simV2.VISIT_CELL_QUADRATIC_TET
VISIT_CELL_QUADRATIC_PYR = _simV2.VISIT_CELL_QUADRATIC_PYR
VISIT_CELL_QUADRATIC_WEDGE = _simV2.VISIT_CELL_QUADRATIC_WEDGE
VISIT_CELL_QUADRATIC_HEX = _simV2.VISIT_CELL_QUADRATIC_HEX
VISIT_CELL_BIQUADRATIC_TRI = _simV2.VISIT_CELL_BIQUADRATIC_TRI
VISIT_CELL_BIQUADRATIC_QUAD = _simV2.VISIT_CELL_BIQUADRATIC_QUAD
VISIT_CELL_TRIQUADRATIC_HEX = _simV2.VISIT_CELL_TRIQUADRATIC_HEX
VISIT_CELL_QUADRATIC_LINEAR_QUAD = _simV2.VISIT_CELL_QUADRATIC_LINEAR_QUAD
VISIT_CELL_QUADRATIC_LINEAR_WEDGE = _simV2.VISIT_CELL_QUADRATIC_LINEAR_WEDGE
VISIT_CELL_BIQUADRATIC_QUADRATIC_WEDGE = _simV2.VISIT_CELL_BIQUADRATIC_QUADRATIC_WEDGE
VISIT_CELL_BIQUADRATIC_QUADRATIC_HEX = _simV2.VISIT_CELL_BIQUADRATIC_QUADRATIC_HEX
VISIT_COORD_MODE_SEPARATE = _simV2.VISIT_COORD_MODE_SEPARATE
VISIT_COORD_MODE_INTERLEAVED = _simV2.VISIT_COORD_MODE_INTERLEAVED
VISIT_GHOSTCELL_REAL = _simV2.VISIT_GHOSTCELL_REAL
VISIT_GHOSTCELL_INTERIOR_BOUNDARY = _simV2.VISIT_GHOSTCELL_INTERIOR_BOUNDARY
VISIT_GHOSTCELL_EXTERIOR_BOUNDARY = _simV2.VISIT_GHOSTCELL_EXTERIOR_BOUNDARY
VISIT_GHOSTCELL_ENHANCED_CONNECTIVITY = _simV2.VISIT_GHOSTCELL_ENHANCED_CONNECTIVITY
VISIT_GHOSTCELL_REDUCED_CONNECTIVITY = _simV2.VISIT_GHOSTCELL_REDUCED_CONNECTIVITY
VISIT_GHOSTCELL_BLANK = _simV2.VISIT_GHOSTCELL_BLANK
VISIT_GHOSTCELL_REFINED_AMR_CELL = _simV2.VISIT_GHOSTCELL_REFINED_AMR_CELL
VISIT_GHOSTNODE_REAL = _simV2.VISIT_GHOSTNODE_REAL
VISIT_GHOSTNODE_INTERIOR_BOUNDARY = _simV2.VISIT_GHOSTNODE_INTERIOR_BOUNDARY
VISIT_GHOSTNODE_BLANK = _simV2.VISIT_GHOSTNODE_BLANK
VISIT_GHOSTNODE_COARSE_SIDE = _simV2.VISIT_GHOSTNODE_COARSE_SIDE
VISIT_GHOSTNODE_FINE_SIDE = _simV2.VISIT_GHOSTNODE_FINE_SIDE
VISIT_CSG_QUADRIC_G = _simV2.VISIT_CSG_QUADRIC_G
VISIT_CSG_SPHERE_PR = _simV2.VISIT_CSG_SPHERE_PR
VISIT_CSG_ELLIPSOID_PRRR = _simV2.VISIT_CSG_ELLIPSOID_PRRR
VISIT_CSG_PLANE_G = _simV2.VISIT_CSG_PLANE_G
VISIT_CSG_PLANE_X = _simV2.VISIT_CSG_PLANE_X
VISIT_CSG_PLANE_Y = _simV2.VISIT_CSG_PLANE_Y
VISIT_CSG_PLANE_Z = _simV2.VISIT_CSG_PLANE_Z
VISIT_CSG_PLANE_PN = _simV2.VISIT_CSG_PLANE_PN
VISIT_CSG_PLANE_PPP = _simV2.VISIT_CSG_PLANE_PPP
VISIT_CSG_CYLINDER_PNLR = _simV2.VISIT_CSG_CYLINDER_PNLR
VISIT_CSG_CYLINDER_PPR = _simV2.VISIT_CSG_CYLINDER_PPR
VISIT_CSG_BOX_XYZXYZ = _simV2.VISIT_CSG_BOX_XYZXYZ
VISIT_CSG_CONE_PNLA = _simV2.VISIT_CSG_CONE_PNLA
VISIT_CSG_CONE_PPA = _simV2.VISIT_CSG_CONE_PPA
VISIT_CSG_POLYHEDRON_KF = _simV2.VISIT_CSG_POLYHEDRON_KF
VISIT_CSG_HEX_6F = _simV2.VISIT_CSG_HEX_6F
VISIT_CSG_TET_4F = _simV2.VISIT_CSG_TET_4F
VISIT_CSG_PYRAMID_5F = _simV2.VISIT_CSG_PYRAMID_5F
VISIT_CSG_PRISM_5F = _simV2.VISIT_CSG_PRISM_5F
VISIT_CSG_QUADRATIC_G = _simV2.VISIT_CSG_QUADRATIC_G
VISIT_CSG_CIRCLE_PR = _simV2.VISIT_CSG_CIRCLE_PR
VISIT_CSG_ELLIPSE_PRR = _simV2.VISIT_CSG_ELLIPSE_PRR
VISIT_CSG_LINE_G = _simV2.VISIT_CSG_LINE_G
VISIT_CSG_LINE_X = _simV2.VISIT_CSG_LINE_X
VISIT_CSG_LINE_Y = _simV2.VISIT_CSG_LINE_Y
VISIT_CSG_LINE_PN = _simV2.VISIT_CSG_LINE_PN
VISIT_CSG_LINE_PP = _simV2.VISIT_CSG_LINE_PP
VISIT_CSG_BOX_XYXY = _simV2.VISIT_CSG_BOX_XYXY
VISIT_CSG_ANGLE_PNLA = _simV2.VISIT_CSG_ANGLE_PNLA
VISIT_CSG_ANGLE_PPA = _simV2.VISIT_CSG_ANGLE_PPA
VISIT_CSG_POLYGON_KP = _simV2.VISIT_CSG_POLYGON_KP
VISIT_CSG_TRI_3P = _simV2.VISIT_CSG_TRI_3P
VISIT_CSG_QUAD_4P = _simV2.VISIT_CSG_QUAD_4P
VISIT_CSG_INNER = _simV2.VISIT_CSG_INNER
VISIT_CSG_OUTER = _simV2.VISIT_CSG_OUTER
VISIT_CSG_ON = _simV2.VISIT_CSG_ON
VISIT_CSG_UNION = _simV2.VISIT_CSG_UNION
VISIT_CSG_INTERSECT = _simV2.VISIT_CSG_INTERSECT
VISIT_CSG_DIFF = _simV2.VISIT_CSG_DIFF
VISIT_CSG_COMPLIMENT = _simV2.VISIT_CSG_COMPLIMENT
VISIT_CSG_XFORM = _simV2.VISIT_CSG_XFORM
VISIT_CSG_SWEEP = _simV2.VISIT_CSG_SWEEP
VISIT_IMAGEFORMAT_BMP = _simV2.VISIT_IMAGEFORMAT_BMP
VISIT_IMAGEFORMAT_JPEG = _simV2.VISIT_IMAGEFORMAT_JPEG
VISIT_IMAGEFORMAT_PNG = _simV2.VISIT_IMAGEFORMAT_PNG
VISIT_IMAGEFORMAT_POVRAY = _simV2.VISIT_IMAGEFORMAT_POVRAY
VISIT_IMAGEFORMAT_PPM = _simV2.VISIT_IMAGEFORMAT_PPM
VISIT_IMAGEFORMAT_RGB = _simV2.VISIT_IMAGEFORMAT_RGB
VISIT_IMAGEFORMAT_TIFF = _simV2.VISIT_IMAGEFORMAT_TIFF
VISIT_IMAGEFORMAT_EXR = _simV2.VISIT_IMAGEFORMAT_EXR
VISIT_EXPORT_WRITE_USING_GROUPS = _simV2.VISIT_EXPORT_WRITE_USING_GROUPS
VISIT_EXPORT_GROUP_SIZE = _simV2.VISIT_EXPORT_GROUP_SIZE
VISIT_CINEMA_SPEC_A = _simV2.VISIT_CINEMA_SPEC_A
VISIT_CINEMA_SPEC_C = _simV2.VISIT_CINEMA_SPEC_C
VISIT_CINEMA_SPEC_D = _simV2.VISIT_CINEMA_SPEC_D
VISIT_CINEMA_CAMERA_STATIC = _simV2.VISIT_CINEMA_CAMERA_STATIC
VISIT_CINEMA_CAMERA_PHI_THETA = _simV2.VISIT_CINEMA_CAMERA_PHI_THETA

def VisIt_CommandMetaData_alloc(*args):
    return _simV2.VisIt_CommandMetaData_alloc(*args)

def VisIt_CommandMetaData_free(obj):
    return _simV2.VisIt_CommandMetaData_free(obj)

def VisIt_CommandMetaData_setName(h, arg2):
    return _simV2.VisIt_CommandMetaData_setName(h, arg2)

def VisIt_CommandMetaData_setEnabled(h, arg2):
    return _simV2.VisIt_CommandMetaData_setEnabled(h, arg2)

def VisIt_CSGMesh_alloc(*args):
    return _simV2.VisIt_CSGMesh_alloc(*args)

def VisIt_CSGMesh_free(obj):
    return _simV2.VisIt_CSGMesh_free(obj)

def VisIt_CSGMesh_setRegions(obj, boolops, leftids, rightids):
    return _simV2.VisIt_CSGMesh_setRegions(obj, boolops, leftids, rightids)

def VisIt_CSGMesh_setZonelist(obj, zl):
    return _simV2.VisIt_CSGMesh_setZonelist(obj, zl)

def VisIt_CSGMesh_setBoundaryTypes(obj, csgtypes):
    return _simV2.VisIt_CSGMesh_setBoundaryTypes(obj, csgtypes)

def VisIt_CSGMesh_setBoundaryCoeffs(obj, coeffs):
    return _simV2.VisIt_CSGMesh_setBoundaryCoeffs(obj, coeffs)

def VisIt_CSGMesh_setExtents(obj, min, max):
    return _simV2.VisIt_CSGMesh_setExtents(obj, min, max)

def VisIt_CurveData_alloc(*args):
    return _simV2.VisIt_CurveData_alloc(*args)

def VisIt_CurveData_free(obj):
    return _simV2.VisIt_CurveData_free(obj)

def VisIt_CurveData_setCoordsXY(obj, x, y):
    return _simV2.VisIt_CurveData_setCoordsXY(obj, x, y)

def VisIt_CurveMetaData_alloc(*args):
    return _simV2.VisIt_CurveMetaData_alloc(*args)

def VisIt_CurveMetaData_free(obj):
    return _simV2.VisIt_CurveMetaData_free(obj)

def VisIt_CurveMetaData_setName(h, arg2):
    return _simV2.VisIt_CurveMetaData_setName(h, arg2)

def VisIt_CurveMetaData_setXUnits(h, arg2):
    return _simV2.VisIt_CurveMetaData_setXUnits(h, arg2)

def VisIt_CurveMetaData_setYUnits(h, arg2):
    return _simV2.VisIt_CurveMetaData_setYUnits(h, arg2)

def VisIt_CurveMetaData_setXLabel(h, arg2):
    return _simV2.VisIt_CurveMetaData_setXLabel(h, arg2)

def VisIt_CurveMetaData_setYLabel(h, arg2):
    return _simV2.VisIt_CurveMetaData_setYLabel(h, arg2)

def VisIt_CurvilinearMesh_alloc(*args):
    return _simV2.VisIt_CurvilinearMesh_alloc(*args)

def VisIt_CurvilinearMesh_free(obj):
    return _simV2.VisIt_CurvilinearMesh_free(obj)

def VisIt_CurvilinearMesh_setCoordsXY(obj, dims, x, y):
    return _simV2.VisIt_CurvilinearMesh_setCoordsXY(obj, dims, x, y)

def VisIt_CurvilinearMesh_setCoordsXYZ(obj, dims, x, y, z):
    return _simV2.VisIt_CurvilinearMesh_setCoordsXYZ(obj, dims, x, y, z)

def VisIt_CurvilinearMesh_setCoords2(obj, dims, c):
    return _simV2.VisIt_CurvilinearMesh_setCoords2(obj, dims, c)

def VisIt_CurvilinearMesh_setCoords3(obj, dims, c):
    return _simV2.VisIt_CurvilinearMesh_setCoords3(obj, dims, c)

def VisIt_CurvilinearMesh_setRealIndices(obj, min, max):
    return _simV2.VisIt_CurvilinearMesh_setRealIndices(obj, min, max)

def VisIt_CurvilinearMesh_setBaseIndex(obj, base_index):
    return _simV2.VisIt_CurvilinearMesh_setBaseIndex(obj, base_index)

def VisIt_CurvilinearMesh_setGhostCells(obj, gz):
    return _simV2.VisIt_CurvilinearMesh_setGhostCells(obj, gz)

def VisIt_CurvilinearMesh_setGhostNodes(obj, gn):
    return _simV2.VisIt_CurvilinearMesh_setGhostNodes(obj, gn)

def VisIt_DomainBoundaries_alloc(*args):
    return _simV2.VisIt_DomainBoundaries_alloc(*args)

def VisIt_DomainBoundaries_free(arg1):
    return _simV2.VisIt_DomainBoundaries_free(arg1)

def VisIt_DomainBoundaries_set_type(arg1, arg2):
    return _simV2.VisIt_DomainBoundaries_set_type(arg1, arg2)

def VisIt_DomainBoundaries_set_numDomains(arg1, arg2):
    return _simV2.VisIt_DomainBoundaries_set_numDomains(arg1, arg2)

def VisIt_DomainBoundaries_set_rectIndices(arg1, dom, e):
    return _simV2.VisIt_DomainBoundaries_set_rectIndices(arg1, dom, e)

def VisIt_DomainBoundaries_set_amrIndices(arg1, patch, level, e):
    return _simV2.VisIt_DomainBoundaries_set_amrIndices(arg1, patch, level, e)

def VisIt_DomainBoundaries_set_extents(arg1, dom, e):
    return _simV2.VisIt_DomainBoundaries_set_extents(arg1, dom, e)

def VisIt_DomainBoundaries_add_neighbor(arg1, dom, d, mi, orientation, extents):
    return _simV2.VisIt_DomainBoundaries_add_neighbor(arg1, dom, d, mi, orientation, extents)

def VisIt_DomainBoundaries_finish(arg1, dom):
    return _simV2.VisIt_DomainBoundaries_finish(arg1, dom)

def VisIt_DomainList_alloc(*args):
    return _simV2.VisIt_DomainList_alloc(*args)

def VisIt_DomainList_free(obj):
    return _simV2.VisIt_DomainList_free(obj)

def VisIt_DomainList_setDomains(obj, alldoms, mydoms):
    return _simV2.VisIt_DomainList_setDomains(obj, alldoms, mydoms)

def VisIt_DomainNesting_alloc(*args):
    return _simV2.VisIt_DomainNesting_alloc(*args)

def VisIt_DomainNesting_free(arg1):
    return _simV2.VisIt_DomainNesting_free(arg1)

def VisIt_DomainNesting_set_dimensions(arg1, arg2, arg3, arg4):
    return _simV2.VisIt_DomainNesting_set_dimensions(arg1, arg2, arg3, arg4)

def VisIt_DomainNesting_set_levelRefinement(arg1, arg2, arg3):
    return _simV2.VisIt_DomainNesting_set_levelRefinement(arg1, arg2, arg3)

def VisIt_DomainNesting_set_nestingForPatch(arg1, arg2, arg3, arg4, arg5, arg6):
    return _simV2.VisIt_DomainNesting_set_nestingForPatch(arg1, arg2, arg3, arg4, arg5, arg6)

def VisIt_ExpressionMetaData_alloc(*args):
    return _simV2.VisIt_ExpressionMetaData_alloc(*args)

def VisIt_ExpressionMetaData_free(obj):
    return _simV2.VisIt_ExpressionMetaData_free(obj)

def VisIt_ExpressionMetaData_setName(h, arg2):
    return _simV2.VisIt_ExpressionMetaData_setName(h, arg2)

def VisIt_ExpressionMetaData_setDefinition(h, arg2):
    return _simV2.VisIt_ExpressionMetaData_setDefinition(h, arg2)

def VisIt_ExpressionMetaData_setType(h, arg2):
    return _simV2.VisIt_ExpressionMetaData_setType(h, arg2)

def VisIt_MaterialData_alloc(*args):
    return _simV2.VisIt_MaterialData_alloc(*args)

def VisIt_MaterialData_free(arg1):
    return _simV2.VisIt_MaterialData_free(arg1)

def VisIt_MaterialData_addMaterial(*args):
    return _simV2.VisIt_MaterialData_addMaterial(*args)

def VisIt_MaterialData_appendCells(h, ncells):
    return _simV2.VisIt_MaterialData_appendCells(h, ncells)

def VisIt_MaterialData_addCleanCell(h, cell, matno):
    return _simV2.VisIt_MaterialData_addCleanCell(h, cell, matno)

def VisIt_MaterialData_addMixedCell(h, cell, matnos, mixvf, nmats):
    return _simV2.VisIt_MaterialData_addMixedCell(h, cell, matnos, mixvf, nmats)

def VisIt_MaterialData_setMaterials(obj, matlist):
    return _simV2.VisIt_MaterialData_setMaterials(obj, matlist)

def VisIt_MaterialData_setMixedMaterials(obj, mix_mat, mix_zone, mix_next, mix_vf):
    return _simV2.VisIt_MaterialData_setMixedMaterials(obj, mix_mat, mix_zone, mix_next, mix_vf)

def VisIt_MaterialMetaData_alloc(*args):
    return _simV2.VisIt_MaterialMetaData_alloc(*args)

def VisIt_MaterialMetaData_free(obj):
    return _simV2.VisIt_MaterialMetaData_free(obj)

def VisIt_MaterialMetaData_setName(h, arg2):
    return _simV2.VisIt_MaterialMetaData_setName(h, arg2)

def VisIt_MaterialMetaData_setMeshName(h, arg2):
    return _simV2.VisIt_MaterialMetaData_setMeshName(h, arg2)

def VisIt_MaterialMetaData_addMaterialName(h, arg2):
    return _simV2.VisIt_MaterialMetaData_addMaterialName(h, arg2)

def VisIt_MeshMetaData_alloc(*args):
    return _simV2.VisIt_MeshMetaData_alloc(*args)

def VisIt_MeshMetaData_free(obj):
    return _simV2.VisIt_MeshMetaData_free(obj)

def VisIt_MeshMetaData_setName(h, arg2):
    return _simV2.VisIt_MeshMetaData_setName(h, arg2)

def VisIt_MeshMetaData_setMeshType(h, arg2):
    return _simV2.VisIt_MeshMetaData_setMeshType(h, arg2)

def VisIt_MeshMetaData_setTopologicalDimension(h, arg2):
    return _simV2.VisIt_MeshMetaData_setTopologicalDimension(h, arg2)

def VisIt_MeshMetaData_setSpatialDimension(h, arg2):
    return _simV2.VisIt_MeshMetaData_setSpatialDimension(h, arg2)

def VisIt_MeshMetaData_setNumDomains(h, arg2):
    return _simV2.VisIt_MeshMetaData_setNumDomains(h, arg2)

def VisIt_MeshMetaData_setDomainTitle(h, arg2):
    return _simV2.VisIt_MeshMetaData_setDomainTitle(h, arg2)

def VisIt_MeshMetaData_setDomainPieceName(h, arg2):
    return _simV2.VisIt_MeshMetaData_setDomainPieceName(h, arg2)

def VisIt_MeshMetaData_addDomainName(h, arg2):
    return _simV2.VisIt_MeshMetaData_addDomainName(h, arg2)

def VisIt_MeshMetaData_setNumGroups(h, arg2):
    return _simV2.VisIt_MeshMetaData_setNumGroups(h, arg2)

def VisIt_MeshMetaData_setGroupTitle(h, arg2):
    return _simV2.VisIt_MeshMetaData_setGroupTitle(h, arg2)

def VisIt_MeshMetaData_addGroupName(h, arg2):
    return _simV2.VisIt_MeshMetaData_addGroupName(h, arg2)

def VisIt_MeshMetaData_setGroupPieceName(h, arg2):
    return _simV2.VisIt_MeshMetaData_setGroupPieceName(h, arg2)

def VisIt_MeshMetaData_addGroupId(h, arg2):
    return _simV2.VisIt_MeshMetaData_addGroupId(h, arg2)

def VisIt_MeshMetaData_setXUnits(h, arg2):
    return _simV2.VisIt_MeshMetaData_setXUnits(h, arg2)

def VisIt_MeshMetaData_setYUnits(h, arg2):
    return _simV2.VisIt_MeshMetaData_setYUnits(h, arg2)

def VisIt_MeshMetaData_setZUnits(h, arg2):
    return _simV2.VisIt_MeshMetaData_setZUnits(h, arg2)

def VisIt_MeshMetaData_setXLabel(h, arg2):
    return _simV2.VisIt_MeshMetaData_setXLabel(h, arg2)

def VisIt_MeshMetaData_setYLabel(h, arg2):
    return _simV2.VisIt_MeshMetaData_setYLabel(h, arg2)

def VisIt_MeshMetaData_setZLabel(h, arg2):
    return _simV2.VisIt_MeshMetaData_setZLabel(h, arg2)

def VisIt_MeshMetaData_setCellOrigin(h, arg2):
    return _simV2.VisIt_MeshMetaData_setCellOrigin(h, arg2)

def VisIt_MeshMetaData_setNodeOrigin(h, arg2):
    return _simV2.VisIt_MeshMetaData_setNodeOrigin(h, arg2)

def VisIt_MeshMetaData_setHasSpatialExtents(h, arg2):
    return _simV2.VisIt_MeshMetaData_setHasSpatialExtents(h, arg2)

def VisIt_MeshMetaData_setSpatialExtents(h, arg2):
    return _simV2.VisIt_MeshMetaData_setSpatialExtents(h, arg2)

def VisIt_MeshMetaData_setHasLogicalBounds(h, arg2):
    return _simV2.VisIt_MeshMetaData_setHasLogicalBounds(h, arg2)

def VisIt_MeshMetaData_setLogicalBounds(h, arg2):
    return _simV2.VisIt_MeshMetaData_setLogicalBounds(h, arg2)

def VisIt_NameList_alloc(*args):
    return _simV2.VisIt_NameList_alloc(*args)

def VisIt_NameList_free(obj):
    return _simV2.VisIt_NameList_free(obj)

def VisIt_NameList_addName(h, arg2):
    return _simV2.VisIt_NameList_addName(h, arg2)

def VisIt_OptionList_alloc(*args):
    return _simV2.VisIt_OptionList_alloc(*args)

def VisIt_OptionList_free(obj):
    return _simV2.VisIt_OptionList_free(obj)

def VisIt_OptionList_setValueB(h, arg2, arg3):
    return _simV2.VisIt_OptionList_setValueB(h, arg2, arg3)

def VisIt_OptionList_setValueI(h, arg2, arg3):
    return _simV2.VisIt_OptionList_setValueI(h, arg2, arg3)

def VisIt_OptionList_setValueF(h, arg2, arg3):
    return _simV2.VisIt_OptionList_setValueF(h, arg2, arg3)

def VisIt_OptionList_setValueD(h, arg2, arg3):
    return _simV2.VisIt_OptionList_setValueD(h, arg2, arg3)

def VisIt_OptionList_setValueS(h, arg2, arg3):
    return _simV2.VisIt_OptionList_setValueS(h, arg2, arg3)

def VisIt_PointMesh_alloc(*args):
    return _simV2.VisIt_PointMesh_alloc(*args)

def VisIt_PointMesh_free(obj):
    return _simV2.VisIt_PointMesh_free(obj)

def VisIt_PointMesh_setCoordsXY(obj, x, y):
    return _simV2.VisIt_PointMesh_setCoordsXY(obj, x, y)

def VisIt_PointMesh_setCoordsXYZ(obj, x, y, z):
    return _simV2.VisIt_PointMesh_setCoordsXYZ(obj, x, y, z)

def VisIt_PointMesh_setCoords(obj, c):
    return _simV2.VisIt_PointMesh_setCoords(obj, c)

def VisIt_RectilinearMesh_alloc(*args):
    return _simV2.VisIt_RectilinearMesh_alloc(*args)

def VisIt_RectilinearMesh_free(obj):
    return _simV2.VisIt_RectilinearMesh_free(obj)

def VisIt_RectilinearMesh_setCoordsXY(obj, x, y):
    return _simV2.VisIt_RectilinearMesh_setCoordsXY(obj, x, y)

def VisIt_RectilinearMesh_setCoordsXYZ(obj, x, y, z):
    return _simV2.VisIt_RectilinearMesh_setCoordsXYZ(obj, x, y, z)

def VisIt_RectilinearMesh_setRealIndices(obj, min, max):
    return _simV2.VisIt_RectilinearMesh_setRealIndices(obj, min, max)

def VisIt_RectilinearMesh_setBaseIndex(obj, base_index):
    return _simV2.VisIt_RectilinearMesh_setBaseIndex(obj, base_index)

def VisIt_RectilinearMesh_setGhostCells(obj, gz):
    return _simV2.VisIt_RectilinearMesh_setGhostCells(obj, gz)

def VisIt_RectilinearMesh_setGhostNodes(obj, gn):
    return _simV2.VisIt_RectilinearMesh_setGhostNodes(obj, gn)

def VisIt_SimulationMetaData_alloc(*args):
    return _simV2.VisIt_SimulationMetaData_alloc(*args)

def VisIt_SimulationMetaData_free(arg1):
    return _simV2.VisIt_SimulationMetaData_free(arg1)

def VisIt_SimulationMetaData_setMode(h, mode):
    return _simV2.VisIt_SimulationMetaData_setMode(h, mode)

def VisIt_SimulationMetaData_setCycleTime(h, cycle, time):
    return _simV2.VisIt_SimulationMetaData_setCycleTime(h, cycle, time)

def VisIt_SimulationMetaData_addMesh(h, obj):
    return _simV2.VisIt_SimulationMetaData_addMesh(h, obj)

def VisIt_SimulationMetaData_addVariable(h, obj):
    return _simV2.VisIt_SimulationMetaData_addVariable(h, obj)

def VisIt_SimulationMetaData_addMaterial(h, obj):
    return _simV2.VisIt_SimulationMetaData_addMaterial(h, obj)

def VisIt_SimulationMetaData_addCurve(h, obj):
    return _simV2.VisIt_SimulationMetaData_addCurve(h, obj)

def VisIt_SimulationMetaData_addExpression(h, obj):
    return _simV2.VisIt_SimulationMetaData_addExpression(h, obj)

def VisIt_SimulationMetaData_addSpecies(h, obj):
    return _simV2.VisIt_SimulationMetaData_addSpecies(h, obj)

def VisIt_SimulationMetaData_addGenericCommand(h, obj):
    return _simV2.VisIt_SimulationMetaData_addGenericCommand(h, obj)

def VisIt_SimulationMetaData_addCustomCommand(h, obj):
    return _simV2.VisIt_SimulationMetaData_addCustomCommand(h, obj)

def VisIt_SimulationMetaData_addMessage(h, obj):
    return _simV2.VisIt_SimulationMetaData_addMessage(h, obj)

def VisIt_SpeciesData_alloc(*args):
    return _simV2.VisIt_SpeciesData_alloc(*args)

def VisIt_SpeciesData_free(obj):
    return _simV2.VisIt_SpeciesData_free(obj)

def VisIt_SpeciesData_addSpeciesName(h, arg2):
    return _simV2.VisIt_SpeciesData_addSpeciesName(h, arg2)

def VisIt_SpeciesData_setSpecies(h, arg2):
    return _simV2.VisIt_SpeciesData_setSpecies(h, arg2)

def VisIt_SpeciesData_setSpeciesMF(h, arg2):
    return _simV2.VisIt_SpeciesData_setSpeciesMF(h, arg2)

def VisIt_SpeciesData_setMixedSpecies(h, arg2):
    return _simV2.VisIt_SpeciesData_setMixedSpecies(h, arg2)

def VisIt_SpeciesMetaData_alloc(*args):
    return _simV2.VisIt_SpeciesMetaData_alloc(*args)

def VisIt_SpeciesMetaData_free(obj):
    return _simV2.VisIt_SpeciesMetaData_free(obj)

def VisIt_SpeciesMetaData_setName(h, arg2):
    return _simV2.VisIt_SpeciesMetaData_setName(h, arg2)

def VisIt_SpeciesMetaData_setMeshName(h, arg2):
    return _simV2.VisIt_SpeciesMetaData_setMeshName(h, arg2)

def VisIt_SpeciesMetaData_setMaterialName(h, arg2):
    return _simV2.VisIt_SpeciesMetaData_setMaterialName(h, arg2)

def VisIt_SpeciesMetaData_addSpeciesName(h, arg2):
    return _simV2.VisIt_SpeciesMetaData_addSpeciesName(h, arg2)

def VisIt_UnstructuredMesh_alloc(*args):
    return _simV2.VisIt_UnstructuredMesh_alloc(*args)

def VisIt_UnstructuredMesh_free(obj):
    return _simV2.VisIt_UnstructuredMesh_free(obj)

def VisIt_UnstructuredMesh_setCoordsXY(obj, x, y):
    return _simV2.VisIt_UnstructuredMesh_setCoordsXY(obj, x, y)

def VisIt_UnstructuredMesh_setCoordsXYZ(obj, x, y, z):
    return _simV2.VisIt_UnstructuredMesh_setCoordsXYZ(obj, x, y, z)

def VisIt_UnstructuredMesh_setCoords(obj, c):
    return _simV2.VisIt_UnstructuredMesh_setCoords(obj, c)

def VisIt_UnstructuredMesh_setConnectivity(obj, nCells, c):
    return _simV2.VisIt_UnstructuredMesh_setConnectivity(obj, nCells, c)

def VisIt_UnstructuredMesh_setRealIndices(obj, min, max):
    return _simV2.VisIt_UnstructuredMesh_setRealIndices(obj, min, max)

def VisIt_UnstructuredMesh_setGhostCells(obj, gz):
    return _simV2.VisIt_UnstructuredMesh_setGhostCells(obj, gz)

def VisIt_UnstructuredMesh_setGhostNodes(obj, gn):
    return _simV2.VisIt_UnstructuredMesh_setGhostNodes(obj, gn)

def VisIt_UnstructuredMesh_setGlobalCellIds(obj, glz):
    return _simV2.VisIt_UnstructuredMesh_setGlobalCellIds(obj, glz)

def VisIt_UnstructuredMesh_setGlobalNodeIds(obj, gln):
    return _simV2.VisIt_UnstructuredMesh_setGlobalNodeIds(obj, gln)

def VisIt_VariableData_alloc(*args):
    return _simV2.VisIt_VariableData_alloc(*args)

def VisIt_VariableData_free(arg1):
    return _simV2.VisIt_VariableData_free(arg1)

def VisIt_VariableData_setDataC(*args):
    return _simV2.VisIt_VariableData_setDataC(*args)

def VisIt_VariableData_setDataI(*args):
    return _simV2.VisIt_VariableData_setDataI(*args)

def VisIt_VariableData_setDataL(obj, owner, nComps, nTuples, arg5):
    return _simV2.VisIt_VariableData_setDataL(obj, owner, nComps, nTuples, arg5)

def VisIt_VariableData_setDataF(*args):
    return _simV2.VisIt_VariableData_setDataF(*args)

def VisIt_VariableData_setDataD(*args):
    return _simV2.VisIt_VariableData_setDataD(*args)

def VisIt_VariableData_setData(arg1, arg2, arg3, arg4, arg5, arg6):
    return _simV2.VisIt_VariableData_setData(arg1, arg2, arg3, arg4, arg5, arg6)

def VisIt_VariableData_setDataEx(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8):
    return _simV2.VisIt_VariableData_setDataEx(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)

def VisIt_VariableData_setArrayDataC(obj, arrIndex, owner, nTuples, byteOffset, byteStride, arg7):
    return _simV2.VisIt_VariableData_setArrayDataC(obj, arrIndex, owner, nTuples, byteOffset, byteStride, arg7)

def VisIt_VariableData_setArrayDataI(obj, arrIndex, owner, nTuples, byteOffset, byteStride, arg7):
    return _simV2.VisIt_VariableData_setArrayDataI(obj, arrIndex, owner, nTuples, byteOffset, byteStride, arg7)

def VisIt_VariableData_setArrayDataL(obj, arrIndex, owner, nTuples, byteOffset, byteStride, arg7):
    return _simV2.VisIt_VariableData_setArrayDataL(obj, arrIndex, owner, nTuples, byteOffset, byteStride, arg7)

def VisIt_VariableData_setArrayDataF(obj, arrIndex, owner, nTuples, byteOffset, byteStride, arg7):
    return _simV2.VisIt_VariableData_setArrayDataF(obj, arrIndex, owner, nTuples, byteOffset, byteStride, arg7)

def VisIt_VariableData_setArrayDataD(obj, arrIndex, owner, nTuples, byteOffset, byteStride, arg7):
    return _simV2.VisIt_VariableData_setArrayDataD(obj, arrIndex, owner, nTuples, byteOffset, byteStride, arg7)

def VisIt_VariableMetaData_alloc(*args):
    return _simV2.VisIt_VariableMetaData_alloc(*args)

def VisIt_VariableMetaData_free(obj):
    return _simV2.VisIt_VariableMetaData_free(obj)

def VisIt_VariableMetaData_setName(h, arg2):
    return _simV2.VisIt_VariableMetaData_setName(h, arg2)

def VisIt_VariableMetaData_setMeshName(h, arg2):
    return _simV2.VisIt_VariableMetaData_setMeshName(h, arg2)

def VisIt_VariableMetaData_setUnits(h, arg2):
    return _simV2.VisIt_VariableMetaData_setUnits(h, arg2)

def VisIt_VariableMetaData_setCentering(h, arg2):
    return _simV2.VisIt_VariableMetaData_setCentering(h, arg2)

def VisIt_VariableMetaData_setType(h, arg2):
    return _simV2.VisIt_VariableMetaData_setType(h, arg2)

def VisIt_VariableMetaData_setTreatAsASCII(h, arg2):
    return _simV2.VisIt_VariableMetaData_setTreatAsASCII(h, arg2)

def VisIt_VariableMetaData_setHideFromGUI(h, arg2):
    return _simV2.VisIt_VariableMetaData_setHideFromGUI(h, arg2)

def VisIt_VariableMetaData_setNumComponents(h, arg2):
    return _simV2.VisIt_VariableMetaData_setNumComponents(h, arg2)

def VisIt_VariableMetaData_addMaterialName(h, arg2):
    return _simV2.VisIt_VariableMetaData_addMaterialName(h, arg2)

def VisIt_VariableMetaData_setEnumerationType(h, arg2):
    return _simV2.VisIt_VariableMetaData_setEnumerationType(h, arg2)

def VisIt_VariableMetaData_addEnumGraphEdge(h, arg2, arg3, arg4):
    return _simV2.VisIt_VariableMetaData_addEnumGraphEdge(h, arg2, arg3, arg4)

def VisIt_VariableMetaData_addEnumNameValue(h, arg2, arg3, arg4):
    return _simV2.VisIt_VariableMetaData_addEnumNameValue(h, arg2, arg3, arg4)

def VisIt_VariableMetaData_addEnumNameRange(h, arg2, arg3, arg4, arg5):
    return _simV2.VisIt_VariableMetaData_addEnumNameRange(h, arg2, arg3, arg4, arg5)

def VisIt_VariableMetaData_setEnumAlwaysExcludeValue(h, arg2):
    return _simV2.VisIt_VariableMetaData_setEnumAlwaysExcludeValue(h, arg2)

def VisIt_VariableMetaData_setEnumAlwaysExcludeRange(h, arg2, arg3):
    return _simV2.VisIt_VariableMetaData_setEnumAlwaysExcludeRange(h, arg2, arg3)

def VisIt_VariableMetaData_setEnumAlwaysIncludeValue(h, arg2):
    return _simV2.VisIt_VariableMetaData_setEnumAlwaysIncludeValue(h, arg2)

def VisIt_VariableMetaData_setEnumAlwaysIncludeRange(h, arg2, arg3):
    return _simV2.VisIt_VariableMetaData_setEnumAlwaysIncludeRange(h, arg2, arg3)


